# Generated by Django 4.1 on 2022-10-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_shame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Corruptor',
        ),
    ]
