# Generated by Django 4.1 on 2022-11-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_shame', '0002_rename_task_corruptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corruptor',
            name='image',
        ),
    ]
