# Generated by Django 4.1 on 2022-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_shame', '0003_remove_corruptor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptor',
            name='arrested_date',
            field=models.CharField(max_length=100),
        ),
    ]
