# Generated by Django 4.1 on 2022-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_shame', '0004_alter_corruptor_arrested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptor',
            name='arrested_date',
            field=models.DateField(),
        ),
    ]
