# Generated by Django 4.1 on 2022-10-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_captured', models.BooleanField()),
                ('date_created', models.DateTimeField()),
                ('date_captured', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='')),
                ('upvote_count', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.userprofile')),
            ],
        ),
    ]
