# Generated by Django 4.1 on 2022-10-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_content_userprofile_alias_contentupvote_and_more'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='date_captured',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='is_captured',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='upvote_count',
        ),
        migrations.AddField(
            model_name='forum',
            name='contents',
            field=models.ManyToManyField(to='authen.content'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
                ('subscriptor', models.ManyToManyField(to='authen.userprofile')),
            ],
        ),
    ]
