# Generated by Django 4.1 on 2022-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_date_captured_remove_forum_is_captured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
