# Generated by Django 4.1 on 2022-10-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_captured', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_captured', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.CreateModel(
            name='ContentUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authen.content')),
                ('upvoter', models.ManyToManyField(to='authen.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.userprofile'),
        ),
    ]
