# Generated by Django 4.1 on 2022-10-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_content_upvote_count'),
        ('authen', '0004_userprofile_is_admin'),
    ]

    operations = [
    ]
