# Generated by Django 4.1 on 2022-10-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0004_userprofile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authen.userprofile')),
                ('active_since', models.DateField(auto_now_add=True)),
            ],
            bases=('authen.userprofile',),
        ),
    ]
